### ISSUE TITLE
Dev fee mining seems to fault.

### ISSUE THREAD

**Issue by geemodo** [mining-visualizer/MVis-tokenminer#1]
Once switched to user mode, operation continues. Connection error also shows up in user mode as well but works out well.
d16 01:10:47.786> Switching to dev fee mining.  Thank-you for your support!!
d16 01:10:58.283> An error occurred communicating with the node : Exception -32003 : Client connector error: libcurl error: 28 -> Operation timed out
d16 01:10:58.291> Trying again in 5 seconds ...
d16 01:11:03.295> Connecting to node at http://mike.rs:8586 ...
d16 01:11:04.051> Connection established.
d16 01:13:00.531> New challenge : f6c8f0be
d16 01:13:56.324> New challenge : e5dc6974
d16 01:15:17.355> An error occurred communicating with the node : Exception -32003 : Client connector error: libcurl error: 28 -> Operation timed out
d16 01:15:17.369> Trying again in 5 seconds ...
d16 01:15:22.373> Connecting to node at http://mike.rs:8586 ...
d16 01:15:23.015> Connection established.
d16 01:15:42.816> Error in routine tokenBalance: Exception -32003 : Client connector error: libcurl error: 28 -> Operation timed out
d16 01:15:43.207> Switching to user mining.  Your contributions are appreciated!!
d16 01:15:43.413> Solution found; Submitting to pool
d16 01:16:56.887> New challenge : f7d28755

 Rates: 122.0 MH/s | Temp: 0 | Fan: 0

**Comment by mining-visualizer** [comment]
Thanks for the report.  I'll look into that.

**Comment by mining-visualizer** [comment]
What's your difficulty level at?

**Comment by geemodo** [comment]
Difficulty level is 4096, Understood the issue somewhat, and still letting the fee be there! Now trying to set ChallengeFolder= :)

**Comment by mining-visualizer** [comment]
From what I can tell, this was probably just some temporary internet connection problems you were having, or the mining pool was having some temporary problems.  If you experience this again, please re-open this issue.
