### ISSUE TITLE
Multi GPU NVIDIA AND AMD

### ISSUE THREAD

**Issue by silviotech** [mining-visualizer/MVis-tokenminer#10]
is it possible to multi gpu mine with amd and nvidia

.\tokenminer.exe -G -S -t 2
doesnt work

also tried 
.\tokenminer.exe -G -S -t 2 --opencl-devices 0 2

if i specify each opencl device they can mine individually my vega, or gtx 1070

**Comment by mining-visualizer** [comment]
No, sorry.  That is not  supported.
