### ISSUE TITLE
gas limit

### ISSUE THREAD

**Issue by Twente-Mining** [mining-visualizer/MVis-tokenminer#11]
can you add option to change gas limit?

**Comment by mining-visualizer** [comment]
Currently the gas limit is hard coded at 200,000. See  [FarmClient.h#L238](https://github.com/mining-visualizer/MVis-tokenminer/blob/915b78b8cbd55ddc8cca0c7298d16c7e76093f34/ethminer/FarmClient.h#L238)

Is that not enough for your needs?  What are you mining?

I might add an option, or I might use `eth_estimateGas` to get an estimate of the gas required.

For now, though,  you could just change that line of code and build from source.

**Comment by Twente-Mining** [comment]
I'm working on a new project that needs to have a lot more gas.
Some produced blocks need about 600.000 gas.
I found the gas limit in your files and adapted according. 
Building isn't working (windows) perhaps you could make a new build with a higher limit? 
or an eth_estimateGas like you suggest yourself.

**Comment by Twente-Mining** [comment]
thanks!
