### ISSUE TITLE
Cpu usage

### ISSUE THREAD

**Issue by Twente-Mining** [mining-visualizer/MVis-tokenminer#13]
Hey Mvis,

Do you see room to improve CPU usage? 
on multi gpu systems the miner tends to crash because theres not enough cpu power on a tiny celeron cpu

**Comment by mining-visualizer** [comment]
What OS?
AMD or Nvidia?

**Comment by Twente-Mining** [comment]
Windows, NVidia.
Its over using the cpu so its unable to start some times.
I know for speeds its better to use another miner, but yours is the only one with multi-gpu support in 1 instance

**Comment by mining-visualizer** [comment]
I've heard a few reports of Nvidia users experiencing 100% CPU useage.  I think there might be some bugs in Nvidia's implementation of OpenCL.  Unfortunately I don't have any Nvidia GPU's so I can't test much.

**Comment by Twente-Mining** [comment]
I understand. It only does it this in the initialization phase. 
Once its running cpu usage is a lot lower, happens on Intel Celeron G1840 @ 2.80GHz.
This does not happen on Linux. Works marvelous.
