### ISSUE TITLE
libethcore.so when running tokenminer

### ISSUE THREAD

**Issue by shiggid** [mining-visualizer/MVis-tokenminer#5]
![image](https://user-images.githubusercontent.com/35856714/37813701-470897c8-2ea1-11e8-8951-8d38cffe6476.png)

**Comment by mining-visualizer** [comment]
What OS version is that?

**Comment by shiggid** [comment]
Ubuntu 16.04

On Fri, Mar 23, 2018 at 2:09 PM, Mining Visualizer <notifications@github.com

**Comment by mining-visualizer** [comment]
It looks like I need to ship those dependencies with the executable.  I had assumed everything was statically linked at compile time, like it does under Windows.  Should have a new download package shortly.

**Comment by mining-visualizer** [comment]
v2.1.5 is now available, which hopefully will address this issue. It's a short term hack ... you're basically installing a complete dev environment.  Hopefully I can improve it in the future.  Please try it out and let me know the results.

**Comment by shiggid** [comment]
i still got the same error message not sure why... cant find libethcore.so
and i ran all the commands in INSTALL-LINUX as well

On Sat, Mar 24, 2018 at 7:29 AM, Mining Visualizer <notifications@github.com

**Comment by mining-visualizer** [comment]
> so and i ran all the commands in INSTALL-LINUX as well

Yeah, that was the idea.  I forgot to mention it.  I assume it worked then?

**Comment by shiggid** [comment]
no sorry, didnt finish my sentence before sending the email lol.

I still get the same exact error complaining libethcore.

**Comment by mining-visualizer** [comment]
Well, for now I think I'm just going to recommend building from source.  With the instructions you followed in INSTALL-LINUX, you're 80% there already.

**Comment by shiggid** [comment]
i built it from source... you'll want to  update your instructions:

You can then find the executable in the build/tokenminer subfolder

its actually in the ethminer folder

On Sat, Mar 24, 2018 at 1:31 PM, Mining Visualizer <notifications@github.com

**Comment by mining-visualizer** [comment]
Done.
