### ISSUE TITLE
Miner not working with Powadv token

### ISSUE THREAD

**Issue by dvdrbls** [mining-visualizer/MVis-tokenminer#6]
the miner find blocks but they are all rejected, can you help?
I do have some funds in that ether account

**Comment by mining-visualizer** [comment]
Are you @Cesare from Discord?  He had similar issues to you and I responded there.
Are you solo mining?

**Comment by dvdrbls** [comment]
no I am another user, let me check discord, thanks!

**Comment by dvdrbls** [comment]
My name in discord is Numiner I didn't find the conversation, yes I am solo Mining

**Comment by mining-visualizer** [comment]
Ok, someone else reported the same  problem today,  and it turns out there is a bug in the miner that causes it to mine at too easy a difficulty level, so solutions are rejected by the 0xbtc contract.  Sorry about that.  There is a workaround if you want to get back to solo mining ... just open up tokenminer.ini and set 
```ini
[0xBitcoin]
MinutesPerShare=Pool
```

**Comment by dvdrbls** [comment]
I just did, however Im using this miner to mine Powadv the 0xbitcoin clone and at the moment it is only mineable as solo all those rejected transaccions are mine https://etherscan.io/txs?a=0x1a136ae98b49b92841562b6574d1f3f5b0044e4c

**Comment by dvdrbls** [comment]
Is the contract and not the miner the problem?

**Comment by dvdrbls** [comment]
Found another solution, It was rejected Tx....... Failed, gasPrice = 10 : (

**Comment by mining-visualizer** [comment]
> Im using this miner to mine Powadv the 0xbitcoin clone

You should have said that right at the beginning.  I had just assumed your reference to 'POWA' was a typo.  I have no idea why it is doing that.  I don't officially support that token at the moment.  Things may change in the future.
