### ISSUE TITLE
decimal points on gas

### ISSUE THREAD

**Issue by mikespax** [mining-visualizer/MVis-tokenminer#8]
could you add support for decimals so that I could use 6.1 for the gas fee?

**Comment by mining-visualizer** [comment]
Any particular reason why you need such precision?  I mean, EthGasStation safeLow varies anywhere from 5 to 25 gwei lately.  What difference would a tenth of a gwei make?  Although for completeness sake, I probably should add that feature.  just not sure if it's worth taking the time.

**Comment by mikespax** [comment]
When you're mining low difficulty coins, it doesn't really matter about the
safelow, but about submitting the order before anyone else does. In these
cases, the solution entered with the higher gas prices gets it. Just
experienced these wars a lot myself and looking for all edges. I do know
Cosmic supports the fractions though.

On Jun 7, 2018 6:35 AM, "Mining Visualizer" <notifications@github.com>
wrote:

Any particular reason why you need such precision? I mean, EthGasStation
safeLow varies anywhere from 5 to 25 gwei lately. What difference would a
tenth of a gwei make? Although for completeness sake, I probably should add
that feature. just not sure if it's worth taking the time.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mining-visualizer/MVis-tokenminer/issues/8#issuecomment-395289935>,
or mute the thread
