### ISSUE TITLE
"Switching to dev fee mining" while solo mining

### ISSUE THREAD

**Issue by 0x1d00ffff** [mining-visualizer/MVis-tokenminer#9]
Hi, I noticed that while solo mining I occasionally get "Switching to dev fee mining" and "Switching to user mining" a minute or so later. Is this intentional? I am pretty positive that you would not have embedded a private key into the miner. 

If this time is used for pool mining to a dev address, please disregard this issue. I just figured there is a decent chance this is some unexpected interaction between solo mining and the later added dev fee feature.

**Comment by mining-visualizer** [comment]
Hmm.  It's not supposed to do that.  I'll have to look into that.

**Comment by mining-visualizer** [comment]
Ok, fixed in v2.1.16.  You're right, there was no private key in the program, so any solution found would have been wasted :(
